apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8" 
spec:
  rules:
  - host: {{ pluck .Values.global.env .Values.ingress.host | first | default .Values.ingress.host._default | quote }}
    http:
      paths:
      - path: /auth/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "keycloak.fullname" . }}-http
            port: 
              number: {{ .Values.service.httpPort }}
  tls:
  - hosts:
    - {{ pluck .Values.global.env .Values.ingress.host | first | default .Values.ingress.host._default | quote }}
    secretName: wildcard-crt
